<SplashScreen>
    FloatLayout:
        canvas.before:
            Color:
                rgb: 0.8, 0.4, 0.19, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Video:
            source: 'icones/vitapinasplash.mp4'
            state: 'play'
            options: {'eos': 'loop'}
            allow_stretch: True
            size_hint: None, None
            size: root.size
            pos: root.pos


